### ISSUE TITLE
 Login IBM Cloud 重启失败

### ISSUE THREAD

**Issue by aiastia** [artxia/IBM-gd-utils#11]
Do you want to update? [y/N] > 
FAILED
Unable to authenticate.

##[error]Process completed with exit code 1.

重启的失败 了 这个要怎么搞啊

**Comment by artxia** [comment]
拉取一下最新代码，或者翻看修改记录自己对着改。

重启这里我有个变量写错了，昨天已经修复。
手动：找到auto_restart.yml文件，点编辑，将里面的${{ secrets.IBM_RGN }}改为us-south

**Comment by aiastia** [comment]
auto_restart 这个一直不出来啊。编辑了 也提交了 好像没啥用

**Comment by artxia** [comment]
> auto_restart 这个一直不出来啊。编辑了 也提交了 好像没啥用

这个是定时启动的，如果需要手动启动：
将这段代码加在`on:`下面
```
  workflow_dispatch:
    inputs:
```

**Comment by aiastia** [comment]
````
on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
  schedule:
    - cron: 0 4 * * 5
#  watch:
#    types: [started]

 workflow_dispatch:
    inputs:

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest
````

这样吗？ 好像跑不起来啊
